### ISSUE TITLE
Support Elixir 1.4

### ISSUE THREAD

**Issue by danielwillemse** [bettyblocks/sql_dust#13]
- SqlDust uses String.strip/1 in lib/sql_dust.ex:120.
  This is deprecated in Elixir 1.3. String.trim/1 should be used instead.

- SqlDust uses Enum.partition/2 in lib/sql_dust.ex:101.
  This is deprecated in Elixir 1.3. Enum.split_with/2 should be used instead.

Even though these functions were deprecated in Elixir 1.3, I suggest skipping Elixir 1.3 and just moving on to Elixir 1.4 directly.

**Comment by art4ride** [comment]
NB: `Enum.partition/2` was deprecated only in Elixir 1.4

**Comment by danielwillemse** [comment]
Seems Enum.partition/2 and String.strim/1 deprecations have been reverted.
These no longer give errors or warnings (for me).
So I'm closing this issue.
