### ISSUE TITLE
Ecto 2.0 ?

### ISSUE THREAD

**Issue by keyeh** [bettyblocks/sql_dust#7]
Seems like this is locked to Ecto 1.1? Is an update to Ecto 2 in the works?

```
Failed to use "ecto" because
  sql_dust (version 0.3.6) requires ~> 1.1
  timex_ecto (version 3.0.5) requires ~> 2.0 *
  Locked to 2.0.5 in your mix.loc
```

**Comment by archan937** [comment]
I haven't checked it myself yet but is removing the version constraint sufficient or not?

**Comment by archan937** [comment]
Solved with commit https://github.com/bettyblocks/sql_dust/pull/10/commits/ddb0936a4db02c31dfef892e3d325262d8576a3d
